/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NutAddressList: typeof import('@nutui/nutui-taro')['AddressList']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCascader: typeof import('@nutui/nutui-taro')['Cascader']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutCheckboxGroup: typeof import('@nutui/nutui-taro')['CheckboxGroup']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutEllipsis: typeof import('@nutui/nutui-taro')['Ellipsis']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutPicker: typeof import('@nutui/nutui-taro')['Picker']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutRange: typeof import('@nutui/nutui-taro')['Range']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutSwitch: typeof import('@nutui/nutui-taro')['Switch']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
  }
}
